const book=document.querySelector('#notebook'),about=document.querySelector('#about'),cover=document.querySelector('#cover'),openButton=document.querySelector('#openBook');
function openBook(){book.classList.add('opened');about.inert=false;cover.inert=true;openButton.setAttribute('aria-expanded','true');setTimeout(()=>document.querySelector('#closeBook').focus({preventScroll:true}),850)}
document.querySelectorAll('[data-open]').forEach(el=>el.addEventListener('click',openBook));openButton.addEventListener('click',openBook);
document.querySelector('#closeBook').addEventListener('click',()=>{book.classList.remove('opened');about.inert=true;cover.inert=false;openButton.setAttribute('aria-expanded','false');openButton.focus({preventScroll:true})});
const projects=[
{label:'01 / EDUCATION & PERFORMANCE',title:'把每一条线索，变成更好的机会。',meta:'陕西领头羊教育科技有限公司 · 信息流优化师\n2025.04 — 2026.06',context:'负责职教、技能培训客户在巨量引擎、腾讯广告等平台的获客投放，日常管理预算 1万—2万元。目标是在控制表单成本的同时，提高线索质量。',actions:['重新梳理账户定向，测试新素材，并根据跑量节奏调整出价、定向和投放时段。','每日与销售团队核对线索有效率，定位素材、定向和落地页的问题，形成周度复盘。','独立撰写投放脚本，联动设计制作图文与视频，优化落地页表单并增加智能验证。'],results:'单条线索成本：约 95 元降至约 70 元。\n线索有效率：40% 提升至约 55%。\n“技能补贴申领”系列单条素材最高消耗 1.5万元+；两次获评团队月度优秀优化师。'},
{label:'02 / AI & CONTENT GROWTH',title:'让一个 AI 工具，走进更多人的日常。',meta:'炫图 AI app 推广项目 · 内容运营 & 商务 BD\n2026.05 — 2026.07',context:'参与 AI 修图工具的海内外社媒推广，通过短视频内容和博主合作，为产品冷启动引流。',actions:['拆解小红书、抖音等平台的爆款视频逻辑，制作产品宣传短视频并多平台分发。','监测播放与互动数据，输出每周复盘，持续迭代内容创作方向。','开展达人及素人 BD 建联，搭建按点赞量结算的激励合作模式，并将国内策略复用于海外社媒内容与博主拓展。'],results:'累计产出短视频 120条+。\n合作博主 38位。\n海内外总曝光 80万+。'},
{label:'03 / HOME & LIVING',title:'从看到广告，到想要一个新家。',meta:'肖邦家居（西安）有限公司 · 信息流优化师\n2024.07 — 2025.03',context:'负责家装、家居建材类客户的信息流获客投放，日常管理预算 5000—10000 元。',actions:['完成账户搭建、计划创建与素材上线，根据跑量节奏调整出价、定向和投放时段。','与后端客服每日核对线索有效率，定位无效线索来源，迭代素材与落地页。','围绕“免费量房报价”策划素材，优化表单字段并增加智能验证。'],results:'单条线索成本：约 110 元降至约 85 元。\n线索有效率：42% 提升至约 58%。\n单条素材最高消耗 1万元+，获公司月度通报表扬。'},
{label:'04 / CAMPUS MEDIA',title:'校园里的声音，值得被更多人听见。',meta:'校园融媒体中心 · 内容运营专员 & 活动策划\n2023.09 — 2023.12',context:'围绕校园热点策划内容选题，输出公众号、抖音和小红书内容，并协同团队开展线上线下活动。',actions:['结合校园热点完成选题策划与多平台内容输出。','策划并执行线上线下活动，协同团队完成直播落地。'],results:'单条阅读量突破 10万+。\n账号粉丝增长 50%，平均阅读量提升 80%。\n策划活动 5场，累计参与超 2000人次；协同落地直播 5场。'},
{label:'05 / COMMUNITY & EVENTS',title:'把兴趣聚在一起，让热爱发生连接。',meta:'西安赛福滑板校园推广项目 · 社群运营 & 活动执行\n2024.09 — 2024.11',context:'针对新生群体进行校园推广，从主题活动、兴趣社群到私域转化，连接校园里的滑板爱好者。',actions:['策划面向新生的主题活动，建立兴趣社群，承接私域转化。','统筹 200多人线下活动的现场执行，独立设计活动宣传物料。'],results:'开学月内实现 15笔以上滑板成交。\n内容曝光量提升 20%。\n200多人线下活动零失误落地。'}];
projects.push({label:'FEATURED / PERSONAL TOOL',title:'投放手账｜信息流投放辅助工具',meta:'个人工具项目 · 需求定义、功能策划与 AI 辅助开发',context:'将信息流投放中反复用到的指标计算、素材灵感整理和复盘需求，整合到一个可以在线使用的网页工具里。',actions:['需求定义：围绕信息流投放的日常工作，明确计算、收藏与复盘三个核心场景。','功能策划：组织指标计算、素材灵感收藏和投放复盘功能，形成一个集中的使用入口。','AI 辅助开发：使用 AI 协作制作工具，并通过实际体验反馈调整功能与界面。'],results:'已制作在线版本，支持打开体验。\n访客收藏分别保存。',url:'./flowdesk/'});
const dialog=document.querySelector('#projectDialog'),content=document.querySelector('#dialogContent');content.className='dialog-content';let lastTrigger;
document.querySelectorAll('[data-project]').forEach(button=>button.addEventListener('click',()=>{const p=projects[Number(button.dataset.project)];lastTrigger=button;content.replaceChildren();const add=(tag,text,className)=>{const el=document.createElement(tag);el.textContent=text;if(className)el.className=className;content.append(el);return el};add('span',p.label,'dialog-kicker');const title=add('h2',p.title);title.id='dialogTitle';const meta=add('p',p.meta,'dialog-meta');meta.style.whiteSpace='pre-line';add('h3','项目背景');add('p',p.context);add('h3','我做了什么');const list=add('ul','');p.actions.forEach(t=>{const li=document.createElement('li');li.textContent=t;list.append(li)});add('h3','项目成果');add('div',p.results,'dialog-results').style.whiteSpace='pre-line';if(p.url){const link=add('a','打开投放手账','tool-live-link');link.href=p.url;link.target='_blank';link.rel='noopener';add('p','体验链接的中国大陆网络可达性尚未验证。','source-note')}else{add('p','数据与经历来源：个人简历。','source-note');}dialog.showModal();document.body.style.overflow='hidden';dialog.scrollTop=0}));
document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>{document.body.style.overflow='';lastTrigger?.focus({preventScroll:true})});
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>{const selected=b===button;b.classList.toggle('active',selected);b.setAttribute('aria-pressed',String(selected))});document.querySelectorAll('[data-category]').forEach(card=>{card.hidden=button.dataset.filter!=='all'&&card.dataset.category!==button.dataset.filter});document.querySelector('.small-projects').hidden=['ads','tools'].includes(button.dataset.filter)}));
document.querySelector('#copyEmail').addEventListener('click',async()=>{const toast=document.querySelector('#toast');try{await navigator.clipboard.writeText('1637883387@qq.com');toast.textContent='邮箱已复制，期待你的来信。'}catch{toast.textContent='邮箱：1637883387@qq.com，可长按或选中复制。'}toast.classList.add('visible');setTimeout(()=>toast.classList.remove('visible'),3500)});
