'use client';
import {useEffect,useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {BarChart3,Calculator,Bookmark,Copy,Download,Lightbulb,NotebookPen,RotateCcw} from 'lucide-react';
import {calculate,numberValue} from '@/lib/metrics';
import {materials} from '@/lib/materials';
import {readFavorites,setFavorite} from '@/lib/favorites';
const initial={spend:'',clicks:'',leads:'',valid:'',revenue:'',roi:'',conversion:''};
const sample={spend:'2000',clicks:'800',leads:'40',valid:'28',revenue:'3000',roi:'3',conversion:'10'};
const money=(n:number|null)=>n===null?'—':n.toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
function Field({label,value,onChange,hint,unit,type='number'}:{label:string;value:string;onChange:(s:string)=>void;hint?:string;unit?:string;type?:string}){return <label className="field"><span>{label}</span><div className="input-wrap"><input type={type} min={type==='number'?0:undefined} step="any" value={value} onChange={e=>onChange(e.target.value)} placeholder={type==='number'?'请输入':'请选择日期'}/>{unit&&<span>{unit}</span>}</div>{hint&&<small>{hint}</small>}</label>;}
export default function Home(){
 const [tab,setTab]=useState('calculator'),[v,setV]=useState(initial),[industry,setIndustry]=useState('全部'),[onlySaved,setOnlySaved]=useState(false),[saved,setSaved]=useState<number[]>([]),[loaded,setLoaded]=useState(false),[loadError,setLoadError]=useState(false),[pending,setPending]=useState<number|null>(null);
 const [review,setReview]=useState({date:'',spend:'',cost:'',problem:'',action:''}),[note,setNote]=useState('');
 const metrics=calculate(v); const badInput=Object.values(v).some(x=>x!==''&&numberValue(x)===null); const error=badInput?'请输入有效的非负数字。':metrics.error;
 const update=(key:keyof typeof initial,s:string)=>setV(p=>({...p,[key]:s}));
 async function load(){setLoadError(false);try{setSaved(readFavorites());setLoaded(true);}catch{setLoadError(true);setLoaded(false);}}
 useEffect(()=>{load();setReview(p=>({...p,date:new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}));},[]);
 async function favorite(id:number){if(!loaded||pending!==null)return;setPending(id);const next=!saved.includes(id);try{setSaved(setFavorite(id,next));toast.success(next?'已加入收藏':'已取消收藏');}catch{toast.error('保存失败，请检查浏览器是否允许保存网站数据');}finally{setPending(null);}}
 async function copy(text:string){try{await navigator.clipboard.writeText(text);toast.success('已复制');}catch{toast.error('无法访问剪贴板，请选中文本手动复制');}}
 function generate(){if(!review.date||numberValue(review.spend)===null||numberValue(review.cost)===null||!review.problem.trim()){toast.error('请填写日期、消耗、线索成本和问题点');return;}setNote(`投放复盘｜${review.date}\n\n一、投放数据\n广告消耗：¥${money(numberValue(review.spend))}\n线索成本：¥${money(numberValue(review.cost))} / 条\n\n二、发现的问题\n${review.problem.trim()}\n\n三、下一步行动\n${review.action.trim()||'待补充：明确测试变量、观察周期与判断标准。'}\n\n四、验证记录\n执行后补充实际结果，与本次数据对照。`);toast.success('复盘笔记已生成');}
 function download(){const url=URL.createObjectURL(new Blob([note],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`投放复盘-${review.date||'笔记'}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast.success('已导出 TXT');}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'calculate_ad_metrics',description:'设置投放数据并返回 CPC、线索成本、有效线索率及 ROI 反推成本。',inputSchema:{type:'object',properties:Object.fromEntries(Object.keys(initial).map(k=>[k,{type:'number',minimum:0}])),required:['spend','clicks','leads','valid','revenue','roi','conversion'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:any)=>{if(!input||Object.keys(input).length!==7||Object.keys(initial).some(k=>typeof input[k]!=='number'||!Number.isFinite(input[k])||input[k]<0))throw Error('请输入完整的非负数字');const next=Object.fromEntries(Object.keys(initial).map(k=>[k,String(input[k])])) as typeof initial;const result=calculate(next);if(result.error)throw Error(result.error);setV(next);setTab('calculator');return result;}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 const filtered=materials.filter(m=>(industry==='全部'||m.industry===industry)&&(!onlySaved||saved.includes(m.id)));
 return <><Toaster position="top-center"/><header className="topbar"><div className="brand"><span className="brand-icon"><BarChart3 size={23}/></span><div>投放手账<small>FLOWDESK</small></div></div><span className="edition">信息流投放助手 <b>MVP</b></span></header><main className="shell"><div className="page-heading"><div><div className="eyebrow">你的日常投放工作台</div><h1>把投放，理清楚。</h1><p>算清成本，找到灵感，留下每一次优化的依据。</p></div><div className="heading-note"><span>01 / 计算</span><span>02 / 创作</span><span>03 / 复盘</span></div></div>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="navigation"><TabsTrigger value="calculator"><Calculator/>指标计算器</TabsTrigger><TabsTrigger value="inspiration"><Lightbulb/>素材灵感库</TabsTrigger><TabsTrigger value="review"><NotebookPen/>投放复盘</TabsTrigger></TabsList>
 <TabsContent value="calculator"><div className="section-intro"><div><h2>投放指标计算器</h2><p>填入数据，实时查看成本表现。</p></div><div className="actions"><button className="subtle" onClick={()=>setV(initial)}><RotateCcw size={15}/>清空</button><button className="outline" onClick={()=>setV(sample)}>填入示例</button></div></div><div className="calculator-grid"><section className="panel"><div className="panel-title"><span className="step">01</span><h3>基础投放数据</h3></div><div className="fields"><Field label="广告消耗" value={v.spend} onChange={s=>update('spend',s)} unit="元"/><Field label="点击量" value={v.clicks} onChange={s=>update('clicks',s)} unit="次"/><Field label="总线索量" value={v.leads} onChange={s=>update('leads',s)} unit="条"/><Field label="有效线索量" value={v.valid} onChange={s=>update('valid',s)} unit="条"/></div>{error&&<p className="error" role="alert">{error}</p>}<div className="results" aria-live="polite">{[['CPC · 点击成本',metrics.cpc,'元 / 次'],['CPL · 线索成本',metrics.cpl,'元 / 条'],['有效线索率',metrics.rate===null?null:metrics.rate*100,'%']].map(([label,val,unit],i)=><div className="metric" key={String(label)}><span>{label}</span><strong>{error?'—':i===2?(val===null?'—':Number(val).toFixed(1)):money(val as number|null)}<small>{unit}</small></strong></div>)}</div><div className="formula"><p>CPC = 消耗 ÷ 点击量</p><p>线索成本 = 消耗 ÷ 总线索量</p><p>有效线索率 = 有效线索量 ÷ 总线索量</p><small>分母为 0 或缺少数据时显示「—」。</small></div></section>
 <section className="panel roi-panel"><div className="panel-title"><span className="step">02</span><h3>ROI 目标反推</h3></div><p className="muted">先确定成交目标，再给线索成本划一条线。</p><Field label="每位成交客户的平均收入" value={v.revenue} onChange={s=>update('revenue',s)} unit="元"/><div className="fields"><Field label="目标 ROI" value={v.roi} onChange={s=>update('roi',s)} unit="倍"/><Field label="线索成交率" value={v.conversion} onChange={s=>update('conversion',s)} unit="%"/></div><div className="roi-result" aria-live="polite"><span>可接受的成交获客成本上限</span><strong>¥ {error?'—':money(metrics.cac)}</strong><div><span>对应的线索成本上限</span><b>¥ {error?'—':money(metrics.leadCap)} / 条</b></div></div><p className="formula">获客成本上限 = 客均收入 ÷ 目标 ROI<br/>线索成本上限 = 获客成本上限 × 线索成交率</p><div className="callout">口径：ROI = 成交收入 ÷ 广告消耗。成交率以全部线索为分母；此上限仅考虑广告费用，未扣除履约等经营成本。</div></section></div></TabsContent>
 <TabsContent value="inspiration"><div className="section-intro"><div><h2>广告素材灵感库</h2><p>12 条钩子、痛点话术与留资脚本，改成你的业务表达。</p></div><button className={onlySaved?'primary':'outline'} aria-pressed={onlySaved} onClick={()=>setOnlySaved(!onlySaved)}><Bookmark size={16}/>{onlySaved?'查看全部':'我的收藏'} · {saved.length}</button></div><Tabs value={industry} onValueChange={setIndustry}><TabsList className="filters">{['全部','教培','家装','本地生活'].map(x=><TabsTrigger key={x} value={x}>{x}</TabsTrigger>)}</TabsList></Tabs>{loadError&&<div className="callout error">收藏加载失败。<button className="subtle" onClick={load}>重新加载</button></div>}<div className="materials-grid">{filtered.map(m=><article key={m.id} className="material"><div className="material-meta"><span className={'tag tag-'+m.industry}>{m.industry}</span><span>{m.type}</span><button className="icon-button" aria-label={`${saved.includes(m.id)?'取消收藏':'收藏'}：${m.title}`} aria-pressed={saved.includes(m.id)} disabled={!loaded||pending!==null} onClick={()=>favorite(m.id)}><Bookmark size={19} fill={saved.includes(m.id)?'currentColor':'none'}/></button></div><h3>{m.title}</h3><p className="material-text">{m.text}</p><div className="material-bottom"><small>{m.tip}</small><button className="subtle" onClick={()=>copy(m.text)}><Copy size={15}/>复制</button></div></article>)}</div>{filtered.length===0&&<div className="empty"><Bookmark/><h3>这里还没有收藏</h3><p>先在全部素材中收藏喜欢的文案。</p><button className="outline" onClick={()=>{setOnlySaved(false);setIndustry('全部');}}>浏览全部素材</button></div>}<p className="footnote">收藏按当前浏览器独立保存，清除网站数据后无法恢复，换设备不共享。括号内为待替换内容，发布前请核实业务信息。</p></TabsContent>
 <TabsContent value="review"><div className="section-intro"><div><h2>简易投放复盘</h2><p>把数据、问题和下一步，整理成一份可执行的笔记。</p></div></div><div className="review-grid"><section className="panel"><div className="panel-title"><span className="step">01</span><h3>填写本次投放</h3></div><Field type="date" label="投放日期" value={review.date} onChange={s=>setReview(p=>({...p,date:s}))}/><div className="fields"><Field label="广告消耗" unit="元" value={review.spend} onChange={s=>setReview(p=>({...p,spend:s}))}/><Field label="线索成本" unit="元 / 条" value={review.cost} onChange={s=>setReview(p=>({...p,cost:s}))}/></div><button className="subtle import" onClick={()=>{if(error||metrics.cpl===null||!v.spend){toast.error('请先在计算器填写有效的消耗和线索量');return;}setReview(p=>({...p,spend:v.spend,cost:metrics.cpl!.toFixed(2)}));toast.success('已带入计算器数据');}}>带入计算器数据</button><label className="field"><span>问题点 <em>必填</em></span><textarea value={review.problem} onChange={e=>setReview(p=>({...p,problem:e.target.value}))} placeholder="例如：线索成本上升；部分线索无法联系；素材点击量下降。" rows={4}/></label><label className="field"><span>下一步行动 <em>选填</em></span><textarea value={review.action} onChange={e=>setReview(p=>({...p,action:e.target.value}))} placeholder="例如：替换前 3 秒钩子，保持其他条件一致，观察 2 天后对比线索成本。" rows={3}/></label><button className="primary generate" onClick={generate}><NotebookPen size={17}/>生成复盘笔记</button></section><section className="panel note-panel"><div className="panel-title"><span className="step">02</span><h3>复盘笔记</h3><span className="mini-label">TXT</span></div>{note?<><textarea aria-label="可编辑的复盘笔记" className="note-text" value={note} onChange={e=>setNote(e.target.value)}/><div className="note-actions"><button className="primary" onClick={()=>copy(note)}><Copy size={16}/>复制笔记</button><button className="outline" onClick={download}><Download size={16}/>导出 TXT</button></div><p className="footnote">修改表单后，请重新生成；导出以当前笔记内容为准。</p></>:<div className="note-empty"><NotebookPen size={40}/><h3>每一次投放，都留下一点经验。</h3><p>填写左侧内容并生成，笔记会出现在这里。<br/>生成后可以继续编辑、复制或导出。</p></div>}</section></div></TabsContent>
 </Tabs><footer><span>投放手账 <b>·</b> 从数据到行动</span><span>计算仅供决策参考，以实际投放数据为准</span></footer></main></>;
}
